// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Unity/Assets/Hotfix/Dream/Behaviac/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: Skill/NormalAttack

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Skill_NormalAttack_node1 : behaviac.Condition
	{
		public Condition_bt_Skill_NormalAttack_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ET.SkillAgent)pAgent).IsInAttackArea();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Skill_NormalAttack_node2 : behaviac.Action
	{
		public Action_bt_Skill_NormalAttack_node2()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
			method_p0 = 1;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((ET.SkillAgent)pAgent).DoAttack(method_p0);
			return result;
		}
		int method_p0;
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Skill_NormalAttack_node3 : behaviac.Action
	{
		public Action_bt_Skill_NormalAttack_node3()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
			method_p0 = 2;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((ET.SkillAgent)pAgent).DoAttack(method_p0);
			return result;
		}
		int method_p0;
	}

	public static class bt_Skill_NormalAttack
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Skill/NormalAttack");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("ET.SkillAgent");
#endif
			// children
			{
				IfElse node0 = new IfElse();
				node0.SetClassNameString("IfElse");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("ET.SkillAgent");
#endif
				bt.AddChild(node0);
				{
					Condition_bt_Skill_NormalAttack_node1 node1 = new Condition_bt_Skill_NormalAttack_node1();
					node1.SetClassNameString("Condition");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("ET.SkillAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Action_bt_Skill_NormalAttack_node2 node2 = new Action_bt_Skill_NormalAttack_node2();
					node2.SetClassNameString("Action");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("ET.SkillAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Action_bt_Skill_NormalAttack_node3 node3 = new Action_bt_Skill_NormalAttack_node3();
					node3.SetClassNameString("Action");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("ET.SkillAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
