// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT
using UnityEngine;
///<<< END WRITING YOUR CODE

namespace ET
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

    ///<<< END WRITING YOUR CODE

	public class SkillAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE SkillAgent
    ///<<< END WRITING YOUR CODE
	{
		public bool IsInAttackArea()
		{
///<<< BEGIN WRITING YOUR CODE IsInAttackArea
            Debug.Log($"IsInAttackArea:true");
            return true;
            ///<<< END WRITING YOUR CODE
		}

		public behaviac.EBTStatus DoAttack(int skillindex)
		{
///<<< BEGIN WRITING YOUR CODE DoAttack
            Debug.Log($"DoAttack:{skillindex}");
            return behaviac.EBTStatus.BT_RUNNING;
            ///<<< END WRITING YOUR CODE
		}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

        public Skill skill;

        ///<<< END WRITING YOUR CODE

	}

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

    ///<<< END WRITING YOUR CODE
}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

